name: Test
permissions:
  contents: read

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - run: npm ci

      - run: npm run demo

      - run: npm run test
